server:
  port: 8000

spring:
  jpa:
    generate-ddl: false
    show-sql: false

  # H2 start
#    hibernate:
#      ddl-auto: none
#
#  datasource:
#    url: jdbc:h2:mem:database
#    username: admin
#    password: passwd
#    driver-class-name: org.h2.Driver
#
#  h2:
#    console:
#      enabled: true
  # H2 end

  # Postgresql start
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/database
    username: admin
    password: passwd
    driver-class-name: org.postgresql.Driver
  # Postgresql end

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/rootChangeLog.xml

app:
  security:
    jwt:
      private-key: classpath:certs/jwt-private.pem
      public-key: classpath:certs/jwt-public.pem
      access-exp: 10800000
      refresh-exp: 2592000000

